### PR TITLE
Update webpack config

### PR DESCRIPTION
**Pull request by steverydz**
## Done

- Update webpack config it is inline with other projects
- Add codecov for JS files

## QA

- Check out this feature branch
- Run the site using the command `./run serve` or `dotrun`
- View the site locally in your web browser at: http://0.0.0.0:8012/
- Run through the following [QA steps](https://canonical-web-and-design.github.io/practices/workflow/qa-steps.html)
- Check that there is a `static/js/dist` directory which contains all the built JS files
- Check that the following commands work as expected:
  - `dotrun exec yarn lint-js`
  - `dotrun exec yarn test-js`
  - `dotrun exec yarn build`
  - `dotrun exec yarn watch-js`

### CODE REVIEW

**Comment by carkod** [comment]
@steverydz rebase

**Comment by steverydz** [comment]
@carkod rebase done

**Comment by carkod** [comment]
Build js doesn't exist

**Comment by carkod** [comment]
Oh is it just `build`?

**Comment by steverydz** [comment]
@carkod Sorry, I copy/pasted the instructions from one of the other PRs. There is no `build-js` here, just `build` like you say. I've updated the instructions.

**Pull request merged**
