### PR TITLE
Add meta images to the Yahoo JP and SBI JP pages

### PR DESCRIPTION
**Pull request by solazio**
## Done

- Add meta image to SBi engage page
- Add meta image to Yahoo engage page

## QA

- Got to [/engage/sbi](http://0.0.0.0:8012/engage/sbi) & [/engage/yahoo](http://0.0.0.0:8012/engage/yahoo) and make sure it looks like the live version
- Test it on [https://socialdebug.com/](https://socialdebug.com/) and [https://cards-dev.twitter.com/validator](https://cards-dev.twitter.com/validator)
## Issue / Card

Fixes https://github.com/canonical-web-and-design/web-squad/issues/1480

### CODE REVIEW

**Comment by pmahnke** [comment]
@solazio I don't think it needs extends-with-arg, see #166 for my attempt

**Comment by barrymcgee** [comment]
@solazio Looks good - thanks!

**Comment by barrymcgee** [comment]
My only feedback is to try and keep your commit messages descriptive and don't duplicate them as future us will use the Git log to debug - this is expanded on in our [team practices](https://canonical-web-and-design.github.io/practices/workflow/commit-messages.html).

**Comment by solazio** [comment]
> My only feedback is to try and keep your commit messages descriptive and don't duplicate them as future us will use the Git log to debug - this is expanded on in our [team practices](https://canonical-web-and-design.github.io/practices/workflow/commit-messages.html).
@barrymcgee noted! thanks

**Pull request merged**
