### PR TITLE
Engage pages and takeovers

### LINKED ISSUE #261: Jp.ubuntu.com set up discourse module for engage pages and takeovers
- Add discourse module 2+
- Adjust code to new parsers
- Create base and index templates
- Create templates for homepage takeovers

### PR DESCRIPTION
**Pull request by carkod**
## Done
- Scss linting config consistent with ubuntu.com. so a lot of file formatting.
- Move engage pages to discourse
- Removed html files
- JS homepage takeovers

## QA
- Go to https://jp-ubuntu-com-297.demos.haus and check the homepage takeovers are correct
  - Active takeovers are showing
  - Image sizes are correct
  - They display even if you break the takeovers.json endpoint

- You can see the list of takeovers https://jp-ubuntu-com-297.demos.haus/takeovers
- Go to https://jp-ubuntu-com-297.demos.haus/engage
- Click on list of engage pages, make sure they show and forms work

Edit content: https://discourse.ubuntu.com/t/engage-pages-and-takeovers-for-jp-ubuntu-com/21103

## Reminder before merge
Replace thank-you page absolute links to `https://jp.ubuntu.com`

## Issue / Card

Fix #261

### CODE REVIEW

**Comment by clagom** [comment]
Proposing some changes in how we break the lines of the text, starting from the top.
Before:
before04
After:
after04

**Comment by clagom** [comment]
Before:
before05
After:
after05

**Comment by clagom** [comment]
Before:
before01
After:
after01

**Comment by clagom** [comment]
Before:
before02
After:
after02

**Comment by clagom** [comment]
Before:
before03
After:
after03

**Comment by clagom** [comment]
And last...
Before:
before06
After:
after06

**Comment by carkod** [comment]
@clagom these last 5, can you provide the links? They don't look like engage pages...

**Comment by clagom** [comment]
They are on the home page, scrolling down, not just the takeover

**Comment by carkod** [comment]
Homepage suggestions done.

**Review by anthonydillon — APPROVED** [review]
Code and QA :+1:

**Pull request merged**
